/*
 * codigosLogs.h
 *
 *  Created on: Feb 13, 2025
 *      Author: User
 */

#ifndef INC_CODIGOSLOGS_H_
#define INC_CODIGOSLOGS_H_

enum CODIGOS_LOGS {
	LOG_SISTEMA_INICIADO = 1,

	LOG_IRRIGACAO_AVANCO_SW,
	LOG_IRRIGACAO_REVERSO_SW,
	LOG_DESLOCAMENTO_AVANCO_SW,
	LOG_DESLOCAMENTO_REVERSO_SW,
	LOG_PARADO_SW,

	LOG_IRRIGACAO_AVANCO_APP,
	LOG_IRRIGACAO_REVERSO_APP,
	LOG_DESLOCAMENTO_AVANCO_APP,
	LOG_DESLOCAMENTO_REVERSO_APP,
	LOG_PARADO_APP,

	LOG_IRRIGACAO_AVANCO_EEPROM,
	LOG_IRRIGACAO_REVERSO_EEPROM,
	LOG_DESLOCAMENTO_AVANCO_EEPROM,
	LOG_DESLOCAMENTO_REVERSO_EEPROM,

	LOG_IRRIGACAO_AVANCO_AGENDA,
	LOG_IRRIGACAO_REVERSO_AGENDA,
	LOG_DESLOCAMENTO_AVANCO_AGENDA,
	LOG_DESLOCAMENTO_REVERSO_AGENDA,
	LOG_PARADO_AGENDA,

	LOG_IRRIGACAO_AVANCO_PONTA,
	LOG_IRRIGACAO_REVERSO_PONTA,
	LOG_DESLOCAMENTO_AVANCO_PONTA,
	LOG_DESLOCAMENTO_REVERSO_PONTA,
	LOG_PARADO_PONTA,

	LOG_PARADO_FIM_CURSO,
	LOG_PARADO_HOME,
	LOG_TROCOU_SENTIDO_FIM_CURSO_AVANCO,

	LOG_PARADO_EMERGENCIA,
	LOG_PARADO_FALHA_SEGURANCA,
	LOG_PARADO_BARRICADA,
	LOG_PARADO_BARRICADA_GPS,
	LOG_PARADO_FALTA_FASE,
	LOG_PARADO_FALTA_PRESSAO,
	LOG_PARADO_FALTA_GNSS,

	LOG_PARADO_IHM,

	LOG_TROCOU_SENTIDO_FIM_CURSO_REVERSO
};


#endif /* INC_CODIGOSLOGS_H_ */
